blueprint:
  name: deCONZ - MoesGo TS0044  4-button scene switch
  description: Automate your MoesGo TS0044 4 button scene switch using deCONZ events.
  domain: automation
  input:
    moesgo_ts0044:
      name: MoesGo TS0044 4 button scene switch
      description: MoesGo TS0044 4 button scene switch to use
      selector:
        device:
          integration: deconz
          manufacturer: _TZ3000_abci1hiu
          model: TS0044
    button_one_long_press:
      name: Button 1 (long press)
      description: Action to run on button 1 (lower-left) long press
      default: []
      selector:
        action: {}
    button_one_single_press:
      name: Button 1 (single press)
      description: Action to run on button 1 (lower-left) single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Button 1 (double press)
      description: Action to run on button 1 (lower-left) double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Button 2 (long press)
      description: Action to run on button 2 (lower-right) long press
      default: []
      selector:
        action: {}
    button_two_single_press:
      name: Button 2 (single press)
      description: Action to run on button 2 (lower-right) single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Button 2 (double press)
      description: Action to run on button 2 (lower-right) double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Button 3 (long press)
      description: Action to run on button 3 (upper-right) long press
      default: []
      selector:
        action: {}
    button_three_single_press:
      name: Button 3 (single press)
      description: Action to run on button 3 (upper-right) single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Button 3 (double press)
      description: Action to run on button 3 (upper-right) double press
      default: []
      selector:
        action: {}
    button_four_long_press:
      name: Button 4 (long press)
      description: Action to run on button 4 (upper-left) long press
      default: []
      selector:
        action: {}
    button_four_single_press:
      name: Button 4 (single press)
      description: Action to run on button 4 (upper-left) single press
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Button 4 (double press)
      description: Action to run on button 4 (upper-left) double press
      default: []
      selector:
        action: {}  
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'moesgo_ts0044'
action:
- variables:
    event: '{{ trigger.event.data.event }}'
- choose:
  - conditions:
    - '{{ event == 1003 }}'
    sequence: !input 'button_one_long_press'  
  - conditions:
    - '{{ event == 1002 }}'
    sequence: !input 'button_one_single_press'
  - conditions:
    - '{{ event == 1004 }}'
    sequence: !input 'button_one_double_press'
  - conditions:
    - '{{ event == 2003 }}'
    sequence: !input 'button_two_long_press'
  - conditions:
    - '{{ event == 2002 }}'
    sequence: !input 'button_two_single_press'
  - conditions:
    - '{{ event == 2004 }}'
    sequence: !input 'button_two_double_press'
  - conditions:
    - '{{ event == 3003 }}'
    sequence: !input 'button_three_long_press'
  - conditions:
    - '{{ event == 3002 }}'
    sequence: !input 'button_three_single_press'
  - conditions:
    - '{{ event == 3004 }}'
    sequence: !input 'button_three_double_press'
  - conditions:
    - '{{ event == 4003 }}'
    sequence: !input 'button_four_long_press'
  - conditions:
    - '{{ event == 4002 }}'
    sequence: !input 'button_four_single_press'
  - conditions:
    - '{{ event == 4004 }}'
    sequence: !input 'button_four_double_press'